// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InternalArray struct {
	InternalArray        []int64  `protobuf:"varint,1,rep,packed,name=internal_array,json=internalArray,proto3" json:"internal_array,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalArray) Reset()         { *m = InternalArray{} }
func (m *InternalArray) String() string { return proto.CompactTextString(m) }
func (*InternalArray) ProtoMessage()    {}
func (*InternalArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *InternalArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalArray.Unmarshal(m, b)
}
func (m *InternalArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalArray.Marshal(b, m, deterministic)
}
func (m *InternalArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalArray.Merge(m, src)
}
func (m *InternalArray) XXX_Size() int {
	return xxx_messageInfo_InternalArray.Size(m)
}
func (m *InternalArray) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalArray.DiscardUnknown(m)
}

var xxx_messageInfo_InternalArray proto.InternalMessageInfo

func (m *InternalArray) GetInternalArray() []int64 {
	if m != nil {
		return m.InternalArray
	}
	return nil
}

func init() {
	proto.RegisterType((*InternalArray)(nil), "InternalArray")
}

func init() {
	proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899)
}

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 79 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x32, 0xe3, 0xe2, 0xf5, 0xcc, 0x2b, 0x49, 0x2d, 0xca, 0x4b,
	0xcc, 0x71, 0x2c, 0x2a, 0x4a, 0xac, 0x14, 0x52, 0xe5, 0xe2, 0xcb, 0x84, 0x0a, 0xc4, 0x27, 0x82,
	0x44, 0x24, 0x18, 0x15, 0x98, 0x35, 0x98, 0x83, 0x78, 0x33, 0x91, 0x95, 0x25, 0xb1, 0x81, 0xb5,
	0x1b, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff, 0xa9, 0xc3, 0x51, 0x42, 0x4b, 0x00, 0x00, 0x00,
}
