// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package msg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type InternalArray struct {
	InternalArray        []int64  `protobuf:"varint,1,rep,packed,name=internal_array,json=internalArray,proto3" json:"internal_array,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InternalArray) Reset()         { *m = InternalArray{} }
func (m *InternalArray) String() string { return proto.CompactTextString(m) }
func (*InternalArray) ProtoMessage()    {}
func (*InternalArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *InternalArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InternalArray.Unmarshal(m, b)
}
func (m *InternalArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InternalArray.Marshal(b, m, deterministic)
}
func (m *InternalArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InternalArray.Merge(m, src)
}
func (m *InternalArray) XXX_Size() int {
	return xxx_messageInfo_InternalArray.Size(m)
}
func (m *InternalArray) XXX_DiscardUnknown() {
	xxx_messageInfo_InternalArray.DiscardUnknown(m)
}

var xxx_messageInfo_InternalArray proto.InternalMessageInfo

func (m *InternalArray) GetInternalArray() []int64 {
	if m != nil {
		return m.InternalArray
	}
	return nil
}

// 消消乐-图
type ClearJoyImage struct {
	// 单排-宽度
	Width int32 `protobuf:"varint,1,opt,name=Width,proto3" json:"Width,omitempty"`
	// 高度
	Height int32 `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	// 本体
	Body                 []int64  `protobuf:"varint,3,rep,packed,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClearJoyImage) Reset()         { *m = ClearJoyImage{} }
func (m *ClearJoyImage) String() string { return proto.CompactTextString(m) }
func (*ClearJoyImage) ProtoMessage()    {}
func (*ClearJoyImage) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{1}
}

func (m *ClearJoyImage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClearJoyImage.Unmarshal(m, b)
}
func (m *ClearJoyImage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClearJoyImage.Marshal(b, m, deterministic)
}
func (m *ClearJoyImage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearJoyImage.Merge(m, src)
}
func (m *ClearJoyImage) XXX_Size() int {
	return xxx_messageInfo_ClearJoyImage.Size(m)
}
func (m *ClearJoyImage) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearJoyImage.DiscardUnknown(m)
}

var xxx_messageInfo_ClearJoyImage proto.InternalMessageInfo

func (m *ClearJoyImage) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ClearJoyImage) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ClearJoyImage) GetBody() []int64 {
	if m != nil {
		return m.Body
	}
	return nil
}

type Reply struct {
	Image                *ClearJoyImage `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Reply) Reset()         { *m = Reply{} }
func (m *Reply) String() string { return proto.CompactTextString(m) }
func (*Reply) ProtoMessage()    {}
func (*Reply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{2}
}

func (m *Reply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reply.Unmarshal(m, b)
}
func (m *Reply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reply.Marshal(b, m, deterministic)
}
func (m *Reply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reply.Merge(m, src)
}
func (m *Reply) XXX_Size() int {
	return xxx_messageInfo_Reply.Size(m)
}
func (m *Reply) XXX_DiscardUnknown() {
	xxx_messageInfo_Reply.DiscardUnknown(m)
}

var xxx_messageInfo_Reply proto.InternalMessageInfo

func (m *Reply) GetImage() *ClearJoyImage {
	if m != nil {
		return m.Image
	}
	return nil
}

// 房间信息
type RoomInfo struct {
	// 房间uuid
	RoomUuid string `protobuf:"bytes,1,opt,name=RoomUuid,proto3" json:"RoomUuid,omitempty"`
	// 房间短位id
	RoomShortId string `protobuf:"bytes,2,opt,name=RoomShortId,proto3" json:"RoomShortId,omitempty"`
	// 房间玩家
	RoomPlayerInfo []*RoomPlayerInfo `protobuf:"bytes,3,rep,name=RoomPlayerInfo,proto3" json:"RoomPlayerInfo,omitempty"`
	// 房间地主索引
	RankIndex            int64    `protobuf:"varint,4,opt,name=RankIndex,proto3" json:"RankIndex,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{3}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomUuid() string {
	if m != nil {
		return m.RoomUuid
	}
	return ""
}

func (m *RoomInfo) GetRoomShortId() string {
	if m != nil {
		return m.RoomShortId
	}
	return ""
}

func (m *RoomInfo) GetRoomPlayerInfo() []*RoomPlayerInfo {
	if m != nil {
		return m.RoomPlayerInfo
	}
	return nil
}

func (m *RoomInfo) GetRankIndex() int64 {
	if m != nil {
		return m.RankIndex
	}
	return 0
}

// 房间玩家信息
type RoomPlayerInfo struct {
	// 玩家uuid
	PlayerUuid string `protobuf:"bytes,1,opt,name=PlayerUuid,proto3" json:"PlayerUuid,omitempty"`
	// 玩家shortId
	PlayerShortId string `protobuf:"bytes,2,opt,name=PlayerShortId,proto3" json:"PlayerShortId,omitempty"`
	// 玩家金额
	Balance int64 `protobuf:"varint,3,opt,name=Balance,proto3" json:"Balance,omitempty"`
	// 玩家保险箱金额
	SafeBal              int64    `protobuf:"varint,4,opt,name=SafeBal,proto3" json:"SafeBal,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomPlayerInfo) Reset()         { *m = RoomPlayerInfo{} }
func (m *RoomPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*RoomPlayerInfo) ProtoMessage()    {}
func (*RoomPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{4}
}

func (m *RoomPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomPlayerInfo.Unmarshal(m, b)
}
func (m *RoomPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomPlayerInfo.Marshal(b, m, deterministic)
}
func (m *RoomPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomPlayerInfo.Merge(m, src)
}
func (m *RoomPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_RoomPlayerInfo.Size(m)
}
func (m *RoomPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomPlayerInfo proto.InternalMessageInfo

func (m *RoomPlayerInfo) GetPlayerUuid() string {
	if m != nil {
		return m.PlayerUuid
	}
	return ""
}

func (m *RoomPlayerInfo) GetPlayerShortId() string {
	if m != nil {
		return m.PlayerShortId
	}
	return ""
}

func (m *RoomPlayerInfo) GetBalance() int64 {
	if m != nil {
		return m.Balance
	}
	return 0
}

func (m *RoomPlayerInfo) GetSafeBal() int64 {
	if m != nil {
		return m.SafeBal
	}
	return 0
}

func init() {
	proto.RegisterType((*InternalArray)(nil), "InternalArray")
	proto.RegisterType((*ClearJoyImage)(nil), "ClearJoyImage")
	proto.RegisterType((*Reply)(nil), "reply")
	proto.RegisterType((*RoomInfo)(nil), "RoomInfo")
	proto.RegisterType((*RoomPlayerInfo)(nil), "RoomPlayerInfo")
}

func init() {
	proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899)
}

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x91, 0x41, 0x4b, 0xc3, 0x30,
	0x14, 0xc7, 0x89, 0x5d, 0xa7, 0x7d, 0xa3, 0x13, 0x1e, 0x22, 0x41, 0x44, 0x4a, 0x99, 0xb0, 0x8b,
	0x3b, 0x4c, 0xd0, 0xb3, 0xf3, 0x62, 0x3d, 0x69, 0x86, 0x78, 0x94, 0x68, 0xb3, 0x35, 0x98, 0x26,
	0x23, 0x56, 0xb0, 0x5f, 0xc1, 0x2f, 0xe1, 0x57, 0x95, 0xa4, 0x9d, 0xb6, 0xbb, 0xbd, 0xdf, 0x2f,
	0xaf, 0xff, 0xf7, 0x87, 0x42, 0x54, 0x7e, 0xac, 0x67, 0x1b, 0x6b, 0x2a, 0x93, 0x5e, 0x41, 0x9c,
	0xe9, 0x4a, 0x58, 0xcd, 0xd5, 0x8d, 0xb5, 0xbc, 0xc6, 0x73, 0x18, 0xcb, 0x56, 0xbc, 0x70, 0x67,
	0x28, 0x49, 0x82, 0x69, 0xc0, 0x62, 0xd9, 0x5d, 0x4b, 0x1f, 0x21, 0xbe, 0x55, 0x82, 0xdb, 0x7b,
	0x53, 0x67, 0x25, 0x5f, 0x0b, 0x3c, 0x82, 0xf0, 0x59, 0xe6, 0x55, 0x41, 0x49, 0x42, 0xa6, 0x21,
	0x6b, 0x00, 0x8f, 0x61, 0x78, 0x27, 0xe4, 0xba, 0xa8, 0xe8, 0x9e, 0xd7, 0x2d, 0x21, 0xc2, 0x60,
	0x61, 0xf2, 0x9a, 0x06, 0x3e, 0xdb, 0xcf, 0xe9, 0x05, 0x84, 0x56, 0x6c, 0x54, 0x8d, 0x13, 0x08,
	0xa5, 0xcb, 0xf4, 0x51, 0xa3, 0xf9, 0x78, 0xd6, 0xbb, 0xc4, 0x9a, 0xc7, 0xf4, 0x87, 0xc0, 0x01,
	0x33, 0xa6, 0xcc, 0xf4, 0xca, 0xe0, 0x49, 0x33, 0x3f, 0x7d, 0xca, 0xdc, 0x7f, 0x15, 0xb1, 0x3f,
	0xc6, 0x04, 0x46, 0x6e, 0x5e, 0x16, 0xc6, 0x56, 0x59, 0xee, 0x8b, 0x44, 0xac, 0xab, 0xf0, 0x1a,
	0xc6, 0x0e, 0x1f, 0x14, 0xaf, 0x85, 0x75, 0x79, 0xbe, 0xd7, 0x68, 0x7e, 0x38, 0xeb, 0x6b, 0xb6,
	0xb3, 0x86, 0xa7, 0x10, 0x31, 0xae, 0xdf, 0x33, 0x9d, 0x8b, 0x2f, 0x3a, 0x48, 0xc8, 0x34, 0x60,
	0xff, 0x22, 0xfd, 0x26, 0xbb, 0xb9, 0x78, 0x06, 0xd0, 0x50, 0xa7, 0x69, 0xc7, 0xe0, 0x04, 0xe2,
	0x86, 0xfa, 0x6d, 0xfb, 0x12, 0x29, 0xec, 0x2f, 0xb8, 0xe2, 0xfa, 0x4d, 0xd0, 0xc0, 0x1f, 0xdd,
	0xa2, 0x7b, 0x59, 0xf2, 0x95, 0x58, 0x70, 0xd5, 0xd6, 0xd9, 0xe2, 0xeb, 0xd0, 0xff, 0xef, 0xcb,
	0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x4d, 0x41, 0xa4, 0x48, 0xfc, 0x01, 0x00, 0x00,
}
